const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const themes = [
  'Action',
  'Adventure',
  'Ancient',
  'Animals',
  'Anime',
  'Apocalypse',
  'Arabian',
  'Asian',
  'Aztec',
  'Bars',
  'Battle',
  'Beach',
  'Bells',
  'Best American Style Slots',
  'Bet Slip',
  'Bombs',
  'Bonus Bet',
  'Bonus Buy',
  'Bonus Multiplier',
  'Bonus Wheel',
  'Books',
  'Branded',
  'Buffalos',
  'Candy',
  'Carnival',
  'Cars',
  'Cascading Reels',
  'Cashpots',
  'Cats',
  'Christmas',
  'Circus',
  'Classic',
  'Clover',
  'Cluster Pays',
  'Coin Win',
  'Collect Symbols',
  'Colossal Symbols',
  'Colossal Wilds',
  'Comics',
  'Cowboys',
  'Cyberpunk',
  'Dance',
  'Demons',
  'Detective',
  'Devil',
  'Diamonds',
  'Disco',
  'Double Symbols',
  'Dragons',
  'Dream Drop',
  'Dual Spin',
  'Dynamite',
  'Eagles',
  'Egyptian',
  'Expanding Reels',
  'Expanding Symbols',
  'Expanding Wilds',
  'Extra Reels',
  'Extra Spins',
  'Extra Wilds',
  'Fairy Tales',
  'Fantastic',
  'Fantasy',
  'Festival',
  'Fire',
  'Fish',
  'Fishing',
  'Flowers',
  'Food',
  'Football',
  'Forest',
  'FreeSpins Multiplier',
  'Fruits',
  'Future',
  'Futuristic',
  'Gamble',
  'Gangsters',
  'Gems',
  'Gigablox',
  'Girls',
  'Gladiators',
  'Goblins',
  'Gods',
  'Gold',
  'Greek',
  'Guns',
  'Halloween',
  'Hold and Spin',
  'Hold and Win',
  'Holiday',
  'Horror',
  'Hyper Clusters',
  'Hyper Hold',
  'Increasing Multiplier',
  'Infinity Reels',
  'Jackpot',
  'Japanese',
  'Jewels',
  'Joker',
  'Jungle',
  'Legend',
  'Leprechauns',
  'Level Up',
  'Linked Reels',
  'Locked Reels',
  'Locked Symbols',
  'Locked Wilds',
  'Luxury',
  'Mafia',
  'Magic',
  'Mayan',
  'Mega Fire Blaze',
  'Mega Symbols',
  'Megaclusters',
  'Megaquads',
  'Megaways',
  'Millionways',
  'Mining',
  'Monsters',
  'MultiJump',
  'Multiplier Wilds',
  'Multiplier',
  'Music',
  'Mystery Symbols',
  'Mystic',
  'Mythical',
  'Mythology',
  'Nature',
  'Neon',
  'Nordic',
  'Norse',
  'Nudges',
  'Ocean',
  'Olympus',
  'Oriental',
  'Party',
  'Pick Bonus',
  'Piggy bank',
  'Pirates',
  'Pixel Art Slot Machines',
  'PopWins',
  'Power Reels',
  'Random Multiplier',
  'Random Wilds',
  'Respin Wild',
  'Respins',
  'Retrigger',
  'Retro',
  'Riches',
  'Robots',
  'Rock',
  'Rome',
  'Santa Claus',
  'Scatter Pays',
  'Sea',
  'Sevens',
  'Ships',
  'Slingo',
  'Snow',
  'Space',
  'Special Symbol',
  'Split Symbols',
  'Sports',
  'Spreading Wilds',
  'Stacked Symbols',
  'Stacked Wilds',
  'Stars',
  'Steampunk',
  'Sticky Symbols',
  'Sticky Wilds',
  'Substitution Symbols',
  'Superheroes',
  'Symbol Removal',
  'Symbol Swap',
  'Symbol Upgrade',
  'Synchronizing Reels',
  'Temple',
  'Tiki',
  'TNT',
  'Totem',
  'Trailing Wilds',
  'Transforming Symbols',
  'Treasures',
  'Trolls',
  'Vampires',
  'Vikings',
  'Walking Symbols',
  'Walking Wilds',
  'Warriors',
  'Water',
  'Wild Nudge',
  'Wild Reels',
  'Wild West',
  'Win Both Ways',
  'Winter',
  'Wolf',
  'xNudge',
  'xWays Slots',
  'Zombies',
  'Blitzways',
  'Bonus',
  'Burst Mode',
  'DoubleMax',
  'gem',
  'gol',
  'Hyperspins',
  'Megadozer',
  'Megapays',
  'Meter Pay',
  'MultiMax',
  'Multipop',
  'ni',
  'Nitro Reels',
  'NobleWays',
  'Odin',
  'Poseidon',
  'PowerWays',
  'Queen',
  'Second Chance',
  'Splitz',
  'Thor',
  'Trueways',
  'Voodoo',
  'Ways Boost',
  'Ways Plus',
  'Wild Zones',
  'Wonderways',
  'WowPot',
  'xBet',
  'xBomb',
  'xGOD',
  'xHole',
  'xMental',
  'xMount',
  'xPays',
  'xSplit',
  'XtraHold',
  'XtraWays',
  'xZone',
  'Zeus',
  'Zevs'
];

function createSlug(name) {
  return name.toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
}

async function updateThemes() {
  try {
    console.log('Удаление старых тем...');
    await prisma.themes.deleteMany({});
    console.log('Старые темы удалены.');

    console.log('Добавление новых тем...');
    const themeData = themes.map(name => ({ 
      name, 
      slug: createSlug(name)
    }));
    await prisma.themes.createMany({
      data: themeData
    });
    
    const count = await prisma.themes.count();
    console.log(`Добавлено ${count} тем в базу данных.`);
  } catch (error) {
    console.error('Ошибка при обновлении тем:', error);
  } finally {
    await prisma.$disconnect();
  }
}

updateThemes();