-- Очистка таблицы themes и заполнение новыми фичами слотов
DELETE FROM themes;

-- Вставка новых фичей слотов
INSERT INTO themes (name, slug) VALUES
('Adventure', 'adventure'),
('Ancient', 'ancient'),
('Animals', 'animals'),
('Bonus Bet', 'bonus-bet'),
('Bonus Buy', 'bonus-buy'),
('Books', 'books'),
('Candy', 'candy'),
('Cascading Reels', 'cascading-reels'),
('Christmas', 'christmas'),
('Cluster Pays', 'cluster-pays'),
('Collect Symbols', 'collect-symbols'),
('Cowboys', 'cowboys'),
('Egyptian', 'egyptian'),
('Expanding Symbols', 'expanding-symbols'),
('Fish', 'fish'),
('Fishing', 'fishing'),
('Fruits', 'fruits'),
('Gamble', 'gamble'),
('Gems', 'gems'),
('Gods', 'gods'),
('Gold', 'gold'),
('Greek', 'greek'),
('Guns', 'guns'),
('Holiday', 'holiday'),
('Increasing Multiplier', 'increasing-multiplier'),
('Legend', 'legend'),
('Level Up', 'level-up'),
('Mega Symbols', 'mega-symbols'),
('Megaways', 'megaways'),
('Multiplier', 'multiplier'),
('Multiplier Wilds', 'multiplier-wilds'),
('Music', 'music'),
('Mystery Symbols', 'mystery-symbols'),
('Mythical', 'mythical'),
('Mythology', 'mythology'),
('Nature', 'nature'),
('Nudges', 'nudges'),
('Olympus', 'olympus'),
('Pick Bonus', 'pick-bonus'),
('Random Multiplier', 'random-multiplier'),
('Random Wilds', 'random-wilds'),
('Respins', 'respins'),
('Retrigger', 'retrigger'),
('Santa Claus', 'santa-claus'),
('Scatter Pays', 'scatter-pays'),
('Sea', 'sea'),
('Snow', 'snow'),
('Special Symbol', 'special-symbol'),
('Split Symbols', 'split-symbols'),
('Stacked Symbols', 'stacked-symbols'),
('Stars', 'stars'),
('Sticky Symbols', 'sticky-symbols'),
('Sticky Wilds', 'sticky-wilds'),
('Symbol Swap', 'symbol-swap'),
('Treasures', 'treasures'),
('Warriors', 'warriors'),
('Water', 'water'),
('Wild West', 'wild-west'),
('Winter', 'winter'),
('Zevs', 'zevs'),
('xNudge', 'xnudge'),
('xWays Slots', 'xways-slots');

-- Проверка количества записей
SELECT COUNT(*) as total_themes FROM themes;