export const mockSlots = [
  {
    id: '1',
    name: 'Starburst',
    slug: 'starburst',
    description: 'Classic NetEnt slot with expanding wilds and re-spins',
    thumbnail_url: 'https://via.placeholder.com/300x200?text=Starburst',
    rtp: 96.09,
    volatility: 'low',
    min_bet: 0.1,
    max_bet: 100.0,
    reels: 5,
    rows: 3,
    theme: 'Space/Gems',
    release_date: '2012-01-01',
    rating: 8.5,
    play_count: 15420,
    is_active: true,
    provider: {
      id: '1',
      name: 'NetEnt',
      slug: 'netent',
      description: 'Leading provider of premium gaming solutions',
      founded_year: 1996,
      country: 'Sweden',
    },
    category: {
      id: '1',
      name: 'Video Slots',
      slug: 'video-slots',
      description: 'Modern video slot machines',
    },
  },
  {
    id: '2',
    name: 'Book of Dead',
    slug: 'book-of-dead',
    description: 'Egyptian-themed adventure slot with expanding symbols',
    thumbnail_url: 'https://via.placeholder.com/300x200?text=Book+of+Dead',
    rtp: 96.21,
    volatility: 'high',
    min_bet: 0.01,
    max_bet: 100.0,
    reels: 5,
    rows: 3,
    theme: 'Ancient Egypt',
    release_date: '2016-01-01',
    rating: 9.0,
    play_count: 23150,
    is_active: true,
    provider: {
      id: '2',
      name: "Play'n GO",
      slug: 'playngo',
      description: 'Mobile-first game developer',
      founded_year: 1997,
      country: 'Sweden',
    },
    category: {
      id: '1',
      name: 'Video Slots',
      slug: 'video-slots',
      description: 'Modern video slot machines',
    },
  },
  {
    id: '3',
    name: 'Mega Moolah',
    slug: 'mega-moolah',
    description: 'Famous progressive jackpot slot with African safari theme',
    thumbnail_url: 'https://via.placeholder.com/300x200?text=Mega+Moolah',
    rtp: 88.12,
    volatility: 'medium',
    min_bet: 0.25,
    max_bet: 6.25,
    reels: 5,
    rows: 3,
    theme: 'African Safari',
    release_date: '2006-01-01',
    rating: 8.8,
    play_count: 18750,
    is_active: true,
    provider: {
      id: '3',
      name: 'Microgaming',
      slug: 'microgaming',
      description: 'Pioneer in online gaming software',
      founded_year: 1994,
      country: 'Isle of Man',
    },
    category: {
      id: '2',
      name: 'Jackpot Slots',
      slug: 'jackpot-slots',
      description: 'Progressive and fixed jackpot games',
    },
  },
  {
    id: '4',
    name: "Gonzo's Quest",
    slug: 'gonzos-quest',
    description: 'Adventure slot with cascading reels and multipliers',
    thumbnail_url: 'https://via.placeholder.com/300x200?text=Gonzo%27s+Quest',
    rtp: 95.97,
    volatility: 'medium',
    min_bet: 0.2,
    max_bet: 50.0,
    reels: 5,
    rows: 3,
    theme: 'Adventure',
    release_date: '2010-01-01',
    rating: 8.7,
    play_count: 19200,
    is_active: true,
    provider: {
      id: '1',
      name: 'NetEnt',
      slug: 'netent',
      description: 'Leading provider of premium gaming solutions',
      founded_year: 1996,
      country: 'Sweden',
    },
    category: {
      id: '1',
      name: 'Video Slots',
      slug: 'video-slots',
      description: 'Modern video slot machines',
    },
  },
  {
    id: '5',
    name: 'Immortal Romance',
    slug: 'immortal-romance',
    description: 'Vampire-themed slot with multiple bonus features',
    thumbnail_url: 'https://via.placeholder.com/300x200?text=Immortal+Romance',
    rtp: 96.86,
    volatility: 'medium',
    min_bet: 0.3,
    max_bet: 6.0,
    reels: 5,
    rows: 3,
    theme: 'Vampire/Romance',
    release_date: '2011-01-01',
    rating: 8.9,
    play_count: 21300,
    is_active: true,
    provider: {
      id: '3',
      name: 'Microgaming',
      slug: 'microgaming',
      description: 'Pioneer in online gaming software',
      founded_year: 1994,
      country: 'Isle of Man',
    },
    category: {
      id: '1',
      name: 'Video Slots',
      slug: 'video-slots',
      description: 'Modern video slot machines',
    },
  },
  {
    id: '6',
    name: 'Sweet Bonanza',
    slug: 'sweet-bonanza',
    description: 'Colorful candy-themed slot with tumble feature',
    thumbnail_url: 'https://via.placeholder.com/300x200?text=Sweet+Bonanza',
    rtp: 96.51,
    volatility: 'high',
    min_bet: 0.2,
    max_bet: 125.0,
    reels: 6,
    rows: 5,
    theme: 'Candy/Sweets',
    release_date: '2019-01-01',
    rating: 8.6,
    play_count: 16800,
    is_active: true,
    provider: {
      id: '4',
      name: 'Pragmatic Play',
      slug: 'pragmatic-play',
      description: 'Multi-product content provider',
      founded_year: 2015,
      country: 'Malta',
    },
    category: {
      id: '1',
      name: 'Video Slots',
      slug: 'video-slots',
      description: 'Modern video slot machines',
    },
  },
];

export const mockProviders = [
  {
    id: '1',
    name: 'NetEnt',
    slug: 'netent',
    description: 'Leading provider of premium gaming solutions',
    founded_year: 1996,
    country: 'Sweden',
    is_active: true,
  },
  {
    id: '2',
    name: "Play'n GO",
    slug: 'playngo',
    description: 'Mobile-first game developer',
    founded_year: 1997,
    country: 'Sweden',
    is_active: true,
  },
  {
    id: '3',
    name: 'Microgaming',
    slug: 'microgaming',
    description: 'Pioneer in online gaming software',
    founded_year: 1994,
    country: 'Isle of Man',
    is_active: true,
  },
  {
    id: '4',
    name: 'Pragmatic Play',
    slug: 'pragmatic-play',
    description: 'Multi-product content provider',
    founded_year: 2015,
    country: 'Malta',
    is_active: true,
  },
];
